// packages/upop-react/example/src/combobox-controlled.tsx
import { useCombobox } from '@upop/react';
import cx from 'classnames';
import { useState } from 'react';

import { Book, books, getBooksFilter, itemToString } from './books';

export function ComboboxControlled() {
  const [items, setItems] = useState(books);
  const [isOpen, setIsOpen] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const [selectedItem, setSelectedItem] = useState<Book | null>(null);
  const [inputValue, setInputValue] = useState('');

  const {
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getItemProps,
    getInputProps,
  } = useCombobox({
    items,
    itemToString,
    isOpen,
    onIsOpenChange: ({ isOpen }) => {
      setIsOpen(isOpen);
    },
    highlightedIndex,
    onHighlightedIndexChange: ({ highlightedIndex }) => {
      setHighlightedIndex(highlightedIndex);
    },
    selectedItem,
    onSelectedItemChange: ({ selectedItem }) => {
      setSelectedItem(selectedItem);
    },
    inputValue,
    onInputValueChange: ({ inputValue }) => {
      setInputValue(inputValue);
      setItems(books.filter(getBooksFilter(inputValue)));
    },
  });

  return (
    <div>
      <div className="flex flex-col lg:flex-row gap-4 my-4">
        <button className="btn" onClick={() => setIsOpen(!isOpen)}>
          Toggle open
        </button>

        <button
          className="btn"
          onClick={() => setHighlightedIndex(highlightedIndex - 1)}
        >
          Highlight previous item
        </button>

        <button
          className="btn"
          onClick={() => setHighlightedIndex(highlightedIndex + 1)}
        >
          Highlight next item
        </button>

        <button
          className="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(selectedItem!) - 1])
          }
        >
          Select previous item
        </button>

        <button
          className="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(selectedItem!) + 1])
          }
        >
          Select next item
        </button>

        <button className="btn" onClick={() => setSelectedItem(null)}>
          Clear selected item
        </button>

        <input
          className="input"
          value={inputValue}
          onChange={(event) => setInputValue(event.target.value)}
          placeholder="input value"
        />
      </div>

      <div>
        <div className="w-72 flex flex-col gap-1">
          <label className="w-fit" {...getLabelProps()}>
            Choose your favorite book:
          </label>
          <div className="flex shadow-sm bg-white gap-0.5">
            <input
              placeholder="Best book ever"
              className="w-full p-1.5"
              {...getInputProps()}
            />
            <button
              aria-label="toggle menu"
              className="px-2"
              type="button"
              {...getToggleButtonProps()}
            >
              {isOpen ? <>&#8593;</> : <>&#8595;</>}
            </button>
          </div>
        </div>
        <ul
          className={cx(
            'absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10',
            { hidden: !(isOpen && items.length) },
          )}
          {...getMenuProps()}
        >
          {isOpen &&
            items.map((item, index) => (
              <li
                className={cx(
                  highlightedIndex === index && 'bg-blue-300',
                  selectedItem === item && 'font-bold',
                  'py-2 px-3 shadow-sm flex flex-col',
                )}
                key={item.id}
                {...getItemProps({ item, index })}
              >
                <span>{item.title}</span>
                <span className="text-sm text-gray-700">{item.author}</span>
              </li>
            ))}
        </ul>
      </div>
    </div>
  );
}

// packages/upop-vue/example/src/combobox-controlled.vue
<script setup lang="ts">
import { useCombobox } from '@upop/vue';
import { ref, toRaw } from 'vue';

import { books, itemToString, getBooksFilter, Book } from './books';

const items = ref(books);
const isOpen = ref(false);
const selectedItem = ref<Book | null>(null);
const highlightedIndex = ref(-1);
const inputValue = ref('');

const combobox = useCombobox({
  items: books,
  itemToString,
  isOpen,
  onIsOpenChange(state) {
    isOpen.value = state.isOpen;
  },
  selectedItem,
  onSelectedItemChange(state) {
    selectedItem.value = state.selectedItem;
  },
  highlightedIndex,
  onHighlightedIndexChange(state) {
    highlightedIndex.value = state.highlightedIndex;
  },
  inputValue,
  onInputValueChange(state) {
    inputValue.value = state.inputValue;
    items.value = books.filter(getBooksFilter(state.inputValue));
  },
});
</script>

<template>
  <div>
    <div className="flex flex-col lg:flex-row gap-4 my-4">
      <button class="btn" @click="isOpen = !isOpen">Toggle open</button>

      <button class="btn" @click="highlightedIndex -= 1">
        Highlight previous item
      </button>

      <button class="btn" @click="highlightedIndex += 1">
        Highlight next item
      </button>

      <button
        class="btn"
        @click="selectedItem = books[books.indexOf(toRaw(selectedItem)!) - 1]"
      >
        Select previous item
      </button>

      <button
        class="btn"
        @click="selectedItem = books[books.indexOf(toRaw(selectedItem)!) + 1]"
      >
        Select next item
      </button>

      <button class="btn" @click="selectedItem = null">
        Clear selected item
      </button>

      <input class="input" placeholder="input value" v-model="inputValue" />
    </div>

    <div>
      <div class="w-72 flex flex-col gap-1">
        <label class="w-fit" v-bind="combobox.getLabelProps()">
          Choose your favorite book:
        </label>
        <div class="flex shadow-sm bg-white gap-0.5">
          <input
            placeholder="Best book ever"
            class="w-full p-1.5"
            v-bind="combobox.getInputProps()"
          />
          <button
            aria-label="toggle menu"
            class="px-2"
            type="button"
            v-bind="combobox.getToggleButtonProps()"
          >
            {{ combobox.isOpen ? '&#8593;' : '&#8595;' }}
          </button>
        </div>
      </div>
      <ul
        :class="[
          'absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10',
          { hidden: !(combobox.isOpen && items.length) },
        ]"
        v-bind="combobox.getMenuProps()"
      >
        <li
          v-if="combobox.isOpen"
          v-for="(item, index) in items"
          v-bind="combobox.getItemProps({ item, index })"
          :class="[
            'py-2 px-3 shadow-sm flex flex-col',
            {
              'bg-blue-300': combobox.highlightedIndex === index,
              'font-bold': combobox.selectedItem === item,
            },
          ]"
        >
          <span>{{ item.title }}</span>
          <span class="text-sm text-gray-700">{{ item.author }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>
