// packages/upop-react/example/src/combobox.tsx
import { useCombobox } from '@upop/react';
import cx from 'classnames';
import { useState } from 'react';

import { books, getBooksFilter, itemToString } from './books';

export function ComboBox() {
  const [items, setItems] = useState(books);

  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps,
    getInputProps,
    selectedItem,
  } = useCombobox({
    items,
    itemToString,
    onInputValueChange({ inputValue }) {
      setItems(books.filter(getBooksFilter(inputValue)));
    },
  });

  return (
    <div>
      <div className="w-72 flex flex-col gap-1">
        <label className="w-fit" {...getLabelProps()}>
          Choose your favorite book:
        </label>
        <div className="flex shadow-sm bg-white gap-0.5">
          <input
            placeholder="Best book ever"
            className="w-full p-1.5"
            {...getInputProps()}
          />
          <button
            aria-label="toggle menu"
            className="px-2"
            type="button"
            {...getToggleButtonProps()}
          >
            {isOpen ? <>&#8593;</> : <>&#8595;</>}
          </button>
        </div>
      </div>
      <ul
        className={`absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10 ${
          !(isOpen && items.length) && 'hidden'
        }`}
        {...getMenuProps()}
      >
        {isOpen &&
          items.map((item, index) => (
            <li
              className={cx(
                highlightedIndex === index && 'bg-blue-300',
                selectedItem === item && 'font-bold',
                'py-2 px-3 shadow-sm flex flex-col',
              )}
              key={item.id}
              {...getItemProps({ item, index })}
            >
              <span>{item.title}</span>
              <span className="text-sm text-gray-700">{item.author}</span>
            </li>
          ))}
      </ul>
    </div>
  );
}

// packages/upop-solid/example/src/combobox.tsx
import { createCombobox } from '@upop/solid';
import { createStore } from 'solid-js/store';

import { books, getBooksFilter, itemToString } from './books';

export function Combobox() {
  const [items, setItems] = createStore(books.slice());

  const combobox = createCombobox({
    items,
    itemToString,
    onInputValueChange({ inputValue }) {
      setItems(books.filter(getBooksFilter(inputValue)));
    },
  });

  return (
    <div>
      <div class="w-72 flex flex-col gap-1">
        <label class="w-fit" {...combobox.getLabelProps()}>
          Choose your favorite book:
        </label>
        <div class="flex shadow-sm bg-white gap-0.5">
          <input
            placeholder="Best book ever"
            class="w-full p-1.5"
            {...combobox.getInputProps()}
          />
          <button
            aria-label="toggle menu"
            class="px-2"
            type="button"
            {...combobox.getToggleButtonProps()}
          >
            {combobox.isOpen ? <>&#8593;</> : <>&#8595;</>}
          </button>
        </div>
      </div>
      <ul
        class="absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10"
        classList={{ hidden: !(combobox.isOpen && items.length) }}
        {...combobox.getMenuProps()}
      >
        {combobox.isOpen &&
          items.map((item, index) => (
            <li
              class="py-2 px-3 shadow-sm flex flex-col"
              classList={{
                'bg-blue-300': combobox.highlightedIndex === index,
                'font-bold': combobox.selectedItem === item,
              }}
              {...combobox.getItemProps({ item, index })}
            >
              <span>{item.title}</span>
              <span class="text-sm text-gray-700">{item.author}</span>
            </li>
          ))}
      </ul>
    </div>
  );
}
