// packages/upop-react/example/src/select-controlled.tsx
import cx from 'classnames';
import { useSelect } from '@upop/react';
import { useState } from 'react';

import { Book, books, itemToString } from './books';

export function SelectControlled() {
  const [isOpen, setIsOpen] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const [selectedItem, setSelectedItem] = useState<Book | null>(null);

  const { getToggleButtonProps, getLabelProps, getMenuProps, getItemProps } =
    useSelect({
      items: books,
      itemToString,
      isOpen,
      onIsOpenChange: ({ isOpen }) => {
        setIsOpen(isOpen);
      },
      highlightedIndex,
      onHighlightedIndexChange: ({ highlightedIndex }) => {
        setHighlightedIndex(highlightedIndex);
      },
      selectedItem,
      onSelectedItemChange: ({ selectedItem }) => {
        setSelectedItem(selectedItem);
      },
    });

  return (
    <div>
      <div className="flex flex-col lg:flex-row gap-4 my-4">
        <button className="btn" onClick={() => setIsOpen(!isOpen)}>
          Toggle open
        </button>

        <button
          className="btn"
          onClick={() => setHighlightedIndex(highlightedIndex - 1)}
        >
          Highlight previous item
        </button>

        <button
          className="btn"
          onClick={() => setHighlightedIndex(highlightedIndex + 1)}
        >
          Highlight next item
        </button>

        <button
          className="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(selectedItem!) - 1])
          }
        >
          Select previous item
        </button>

        <button
          className="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(selectedItem!) + 1])
          }
        >
          Select next item
        </button>

        <button className="btn" onClick={() => setSelectedItem(null)}>
          Clear selected item
        </button>
      </div>

      <div className="w-72 flex flex-col gap-1">
        <label {...getLabelProps()}>Choose your favorite book:</label>
        <div
          className="p-2 bg-white flex justify-between cursor-pointer"
          {...getToggleButtonProps()}
        >
          <span>{selectedItem ? selectedItem.title : 'Best book ever'}</span>
          <span className="px-2">{isOpen ? <>&#8593;</> : <>&#8595;</>}</span>
        </div>
      </div>
      <ul
        className={`absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10 ${
          !isOpen && 'hidden'
        }`}
        {...getMenuProps()}
      >
        {isOpen &&
          books.map((item, index) => (
            <li
              className={cx(
                highlightedIndex === index && 'bg-blue-300',
                selectedItem === item && 'font-bold',
                'py-2 px-3 shadow-sm flex flex-col',
              )}
              key={item.id}
              {...getItemProps({ item, index })}
            >
              <span>{item.title}</span>
              <span className="text-sm text-gray-700">{item.author}</span>
            </li>
          ))}
      </ul>
    </div>
  );
}

// packages/upop-solid/example/src/select-controlled.tsx
import { createSelect } from '@upop/solid';
import { createSignal } from 'solid-js';
import { unwrap } from 'solid-js/store';

import { Book, books, itemToString } from './books';

export function SelectControlled() {
  const [isOpen, setIsOpen] = createSignal(false);
  const [selectedItem, setSelectedItem] = createSignal<Book | null>(null);
  const [highlightedIndex, setHighlightedIndex] = createSignal(-1);

  const select = createSelect({
    items: books,
    itemToString,
    isOpen,
    onIsOpenChange: ({ isOpen }) => {
      setIsOpen(isOpen);
    },
    selectedItem,
    onSelectedItemChange: ({ selectedItem }) => {
      setSelectedItem(selectedItem);
    },
    highlightedIndex,
    onHighlightedIndexChange: ({ highlightedIndex }) => {
      setHighlightedIndex(highlightedIndex);
    },
  });

  return (
    <div>
      <div class="flex flex-col lg:flex-row gap-4 my-4">
        <button class="btn" onClick={() => setIsOpen(!isOpen())}>
          Toggle open
        </button>

        <button
          class="btn"
          onClick={() => setHighlightedIndex(highlightedIndex() - 1)}
        >
          Highlight previous item
        </button>

        <button
          class="btn"
          onClick={() => setHighlightedIndex(highlightedIndex() + 1)}
        >
          Highlight next item
        </button>

        <button
          class="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(unwrap(selectedItem()!)) - 1])
          }
        >
          Select previous item
        </button>

        <button
          class="btn"
          onClick={() =>
            setSelectedItem(books[books.indexOf(unwrap(selectedItem())!) + 1])
          }
        >
          Select next item
        </button>

        <button class="btn" onClick={() => setSelectedItem(null)}>
          Clear selected item
        </button>
      </div>

      <div class="w-72 flex flex-col gap-1">
        <label {...select.getLabelProps()}>Choose your favorite book:</label>
        <div
          class="p-2 bg-white flex justify-between cursor-pointer"
          {...select.getToggleButtonProps()}
        >
          <span>
            {select.selectedItem ? select.selectedItem.title : 'Best book ever'}
          </span>
          <span class="px-2">
            {select.isOpen ? <>&#8593;</> : <>&#8595;</>}
          </span>
        </div>
      </div>
      <ul
        class="absolute w-72 bg-white mt-1 shadow-md max-h-80 overflow-scroll p-0 z-10"
        classList={{ hidden: !select.isOpen }}
        {...select.getMenuProps()}
      >
        {select.isOpen &&
          books.map((item, index) => (
            <li
              class="py-2 px-3 shadow-sm flex flex-col"
              classList={{
                'bg-blue-300': select.highlightedIndex === index,
                'font-bold': unwrap(select.selectedItem) === item,
              }}
              {...select.getItemProps({ item, index })}
            >
              <span>{item.title}</span>
              <span class="text-sm text-gray-700">{item.author}</span>
            </li>
          ))}
      </ul>
    </div>
  );
}
